### ISSUE TITLE
Permissions don't allow deleting error or result files 

### ISSUE THREAD

**Issue by egsch** [amordahl/ECSTATIC#6]
The folder the results are stored in (ECSTATIC/results/[tool]/[benchmark]/campaign0) has an incorrect owner set and appears to reset the owner while running. Attempting to remove error or result files from the campaign0 folder causes a "Permission Denied" error.

**Comment by amordahl** [comment]
I (think I) fixed this issue with my most recent commit. Thanks!

Austin Mordahl (he/him/his)
***@***.******@***.***>
——————————————
Sent from mobile.  Please excuse any proofing or formatting errors.

On Jul 6, 2022, at 5:25 PM, Emma Schaumann ***@***.***> wrote:

﻿

The folder the results are stored in (ECSTATIC/results/[tool]/[benchmark]/campaign0) has an incorrect owner set and appears to reset the owner while running. Attempting to remove error or result files from the campaign0 folder causes a "Permission Denied" error.
