### ISSUE TITLE
Wrong build script for project in Dacapo-2006

### ISSUE THREAD

**Issue by Pancax** [amordahl/ECSTATIC#9]
[https://github.com/amordahl/ECSTATIC/blob/master/src/resources/benchmarks/dacapo-2006/index.json](url) 

I think pmd.jar is using charts build script, is this expected?

**Comment by amordahl** [comment]
Probably not. Can you check that there is a build_pmd.sh script in the Dacapo repo? If so, change the index.json file.

**Comment by Pancax** [comment]
Yes fixed in https://github.com/amordahl/ECSTATIC/commit/77eb645a70a4ff36fae380204a5e136c491fcf70
